before_script:
  - docker info

build_backend_test_image:
  stage: build
  script:
    - docker build ./backend/ -t docker.maxiv.lu.se/elogy_backend-test
    - docker push docker.maxiv.lu.se/elogy_backend-test
  only:
    - develop

build_frontend_test_image:
  stage: build
  script:
    - docker build ./frontend/ -t docker.maxiv.lu.se/elogy_frontend-test
    - docker push docker.maxiv.lu.se/elogy_frontend-test
  only:
    - develop

deploy_test_image:
  stage: deploy
  script:
    - 'curl -H "Authorization: Bearer $AWX_TOKEN" -XPOST https://ansible.maxiv.lu.se/api/v2/job_templates/22/launch/'
  only:
    - develop
build_backend_image:
  stage: build
  script:
    - docker build ./backend/ -t docker.maxiv.lu.se/elogy_backend
    - docker push docker.maxiv.lu.se/elogy_backend
  only:
    - master

build_frontend_image:
  stage: build
  script:
    - docker build ./frontend/ -t docker.maxiv.lu.se/elogy_frontend
    - docker push docker.maxiv.lu.se/elogy_frontend
  only:
    - master

deploy_image:
  stage: deploy
  script:
    - 'curl -H "Authorization: Bearer $AWX_TOKEN" -XPOST https://ansible.maxiv.lu.se/api/v2/job_templates/109/launch/'
  only:
    - master
