version: "3"
services:
  balancer:
    build: balancer
    restart: always
    ports:
      - "80:80"
    volumes:
      - /tmp/elogy/log/balancer:/var/log/nginx # Change this!
  backend:
    build: backend
    restart: always
    environment:
      - 'ELOGY_DEBUG=0'
      - 'ELOGY_DATABASE=/var/elogy/db/elogy.db'
      - 'ELOGY_CONFIG_FILE=/app/elogy/config.py'
      - 'ELOGY_UPLOAD_FOLDER=/var/elogy/attachments'
      - 'ELOGY_LDAP_SERVER=srv-ldap-2.maxiv.lu.se'
      - 'ELOGY_LDAP_BASEDN=dc=maxlab,dc=lu,dc=se'
    volumes:
      - /tmp/elogy/db:/var/elogy/db # Change this!
      - /tmp/elogy/attachments:/var/elogy/attachments # Change this!
  frontend:
    build: frontend
    restart: always
    volumes:
      - /tmp/elogy/log/frontend:/var/log/nginx # Change this!