version: "3"
services:
  balancer:
    build: balancer
    restart: always
    ports:
      - "80:80"
    volumes:
      # Change the part to the left of : to select
      # where files end up in the host filesystem.
      - /tmp/elogy/log/balancer:/var/log/nginx
  backend:
    build: backend
    restart: always
    # depends_on:
    #   - "db"
    environment:
      - 'ELOGY_DEBUG=0'
      - 'ELOGY_DATABASE=/var/elogy/db/elogy.db'
      - 'ELOGY_URL=http://localhost'
      - 'ELOGY_SECRET=PQDfjXrwWLWy8C97BYcKV2dteDm76RHXmB'
      - 'ELOGY_CONFIG_FILE=/app/elogy/config.py'
      - 'ELOGY_UPLOAD_FOLDER=/var/elogy/attachments'
      #- 'ELOGY_LDAP_SERVER=srv-ad-2.maxiv.lu.se'
      #- 'ELOGY_LDAP_BASEDN=dc=maxlab,dc=lu,dc=se'
      #- 'ELOGY_LDAP_BIND_USERNAME=nslcd-ad@maxlab.lu.se'
      #- 'ELOGY_LDAP_BIND_PASSWORD=34suzbUzFqHC'
    volumes:
      # Change the part to the left of : to select
      # where files end up in the host filesystem.
      - /tmp/elogy/db:/var/elogy/db
      - /tmp/elogy/attachments:/var/elogy/attachments
  frontend:
    build: frontend
    restart: always
    volumes:
      # Change the part to the left of : to select
      # where files end up in the host filesystem.
      - /tmp/elogy/log/frontend:/var/log/nginx
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: root
  #     POSTGRES_DB: elogy